### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by Tom4sBeltr4n** [matnsc/StudyTimer#11]
I don't feel like the readme or the description are clear enough on its functions, so I'm not sure if it doues what I want or not. I came here from the Firefox add-on store

**Comment by MatNascimento** [comment]
You mean add something like a list of features?

**Comment by Tom4sBeltr4n** [comment]
Yes, something along those lines

**Comment by matnsc** [comment]
The README was updated, it should be more clear about what it's supposed to be and the features it has
