### ISSUE TITLE
Skip option

### ISSUE THREAD

**Issue by a129rn** [matnsc/StudyTimer#3]
Sometimes I accidentally close the browser and the timer restarts again when I open it back up. An option to skip the session you are doing at the moment so that you can get back to where you were before would be great. Also, I think there would be a few people who wouldn't want to enable this because they might cheat so maybe there could be an option in the settings to turn this on or off.

**Comment by a129rn** [comment]
@MatNascimento still looking for a response.

**Comment by MatNascimento** [comment]
This feature is possible to implement using the browser's storage API to persist the session.

I'll try to implement it, but consider its user case really specific, so it will have a lower priority.

**Comment by matnsc** [comment]
I added the option to save the current timer and pomodoros to continue on the same session later (https://github.com/matnsc/StudyTimer/commit/210adc8791841e9415d125f06d7a5c6ab711bcb1).
It isn't a skip button, but it fit the use case you described without the risk of cheating.
